# Generated by Django 5.0 on 2026-04-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome图标类名",
                        max_length=50,
                        verbose_name="图标",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "景点分类",
                "verbose_name_plural": "景点分类",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="景点名称")),
                ("description", models.TextField(verbose_name="景点介绍")),
                ("address", models.CharField(max_length=200, verbose_name="详细地址")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="门票价格",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        default="09:00-17:00", max_length=100, verbose_name="开放时间"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="咨询电话"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="attractions/",
                        verbose_name="景点图片",
                    ),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览次数")),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "景点",
                "verbose_name_plural": "景点",
                "ordering": ["-is_recommended", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="评分",
                    ),
                ),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "attraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.attraction",
                        verbose_name="景点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价",
                "verbose_name_plural": "评价",
            },
        ),
        migrations.CreateModel(
            name="TourPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="套餐名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("day_trip", "一日游"),
                            ("multi_day", "多日游"),
                            ("theme", "主题游"),
                        ],
                        max_length=20,
                        verbose_name="套餐类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="行程介绍")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(default=1, verbose_name="行程天数"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="packages/",
                        verbose_name="套餐图片",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否上架"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "attractions",
                    models.ManyToManyField(
                        to="core.attraction", verbose_name="包含景点"
                    ),
                ),
            ],
            options={
                "verbose_name": "旅游套餐",
                "verbose_name_plural": "旅游套餐",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.CharField(max_length=32, unique=True, verbose_name="订单号"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="预订数量")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总金额"
                    ),
                ),
                ("travel_date", models.DateField(verbose_name="出行日期")),
                (
                    "contact_name",
                    models.CharField(max_length=50, verbose_name="联系人姓名"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已支付"),
                            ("cancelled", "已取消"),
                            ("completed", "已完成"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "tour_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tourpackage",
                        verbose_name="旅游套餐",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "ordering": ["-created_at"],
            },
        ),
    ]
