# Generated by Django 5.0 on 2026-04-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="attraction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.attraction",
                verbose_name="景点",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_type",
            field=models.CharField(
                choices=[("package", "旅游套餐"), ("ticket", "景点门票")],
                default="package",
                max_length=20,
                verbose_name="产品类型",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tour_package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.tourpackage",
                verbose_name="旅游套餐",
            ),
        ),
    ]
